[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.23"
optimizer = true
optimizer_runs = 200
via_ir = true

remappings = [
  "@openzeppelin/=lib/openzeppelin-contracts/",
  "account-abstraction/=lib/account-abstraction/contracts/",
  "forge-std/=lib/forge-std/src/"
]

fs_permissions = [
  { access = "read-write", path = "./deployments" }
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
